stages:
- test

Test:
  stage: test
  image:
    name: ubuntu:24.04
    entrypoint: [ "" ]
  before_script:
    - apt update
    - apt install -y expect
  script:
    - ./run-tests.sh
  artifacts:
    paths:
      - envcraft.sh
    when: on_success
